export const courses = [
  {
    id: 1,
    category: "Datos y Tecnología",
    categoryColor: "from-[#360b7f] to-[#680080]",
    title: "Curso básico para entender sobre software",
    description: "Aprende los fundamentos del desarrollo de software",
    image: "/placeholder.svg?height=300&width=400",
    lessons: 23,
    duration: "1h 30min",
    originalPrice: "$67.00",
    currentPrice: "$32.00",
    isFree: false,
    students: 1250,
    instructor: { name: "Miguel Jhon", avatar: "/placeholder.svg?height=40&width=40", rating: 4.8, reviews: 44 },
  },
  {
    id: 2,
    category: "Mecánica",
    categoryColor: "from-[#680080] to-[#90007e]",
    title: "Curso avanzado para entender sobre software",
    description: "Conceptos avanzados de ingeniería mecánica",
    image: "/placeholder.svg?height=300&width=400",
    lessons: 29,
    duration: "2h 10min",
    originalPrice: "$67.00",
    currentPrice: "$32.00",
    isFree: true,
    students: 890,
    instructor: { name: "Rinis Jhon", avatar: "/placeholder.svg?height=40&width=40", rating: 4.9, reviews: 44 },
  },
  {
    id: 3,
    category: "Desarrollo",
    categoryColor: "from-[#90007e] to-[#CF0072]",
    title: "Curso completo para entender sobre soluciones",
    description: "Dominio del desarrollo full-stack",
    image: "/placeholder.svg?height=300&width=400",
    lessons: 25,
    duration: "1h 40min",
    originalPrice: "$67.00",
    currentPrice: "$40.00",
    isFree: true,
    students: 2100,
    instructor: { name: "Miguel Jhon", avatar: "/placeholder.svg?height=40&width=40", rating: 4.7, reviews: 44 },
  },
  {
    id: 4,
    category: "Diseño UI & UX",
    categoryColor: "from-[#CF0072] to-[#E82769]",
    title: "Curso de diseño para entender sobre soluciones",
    description: "Crea diseños hermosos y funcionales",
    image: "/placeholder.svg?height=300&width=400",
    lessons: 36,
    duration: "3h 40min",
    originalPrice: "$67.00",
    currentPrice: "$40.00",
    isFree: true,
    students: 1750,
    instructor: { name: "Miguel Robin", avatar: "/placeholder.svg?height=40&width=40", rating: 4.8, reviews: 44 },
  },
  {
    id: 5,
    category: "Marketing",
    categoryColor: "from-[#E82769] to-[#360b7f]",
    title: "Fundamentos de Marketing Digital",
    description: "Domina las estrategias de marketing modernas",
    image: "/placeholder.svg?height=300&width=400",
    lessons: 18,
    duration: "2h 20min",
    originalPrice: "$67.00",
    currentPrice: "$35.00",
    isFree: false,
    students: 980,
    instructor: { name: "Sara Wilson", avatar: "/placeholder.svg?height=40&width=40", rating: 4.9, reviews: 52 },
  },
  {
    id: 6,
    category: "Inteligencia Artificial",
    categoryColor: "from-[#360b7f] to-[#90007e]",
    title: "Introducción a la Inteligencia Artificial",
    description: "Aprende los conceptos básicos de IA y Machine Learning",
    image: "/placeholder.svg?height=300&width=400",
    lessons: 32,
    duration: "4h 15min",
    originalPrice: "$89.00",
    currentPrice: "$45.00",
    isFree: false,
    students: 3200,
    instructor: { name: "Carlos Mendez", avatar: "/placeholder.svg?height=40&width=40", rating: 4.9, reviews: 67 },
  },
]
